on:
  workflow_dispatch:
  
name: Deploy Bicep Demo

permissions:
      id-token: write
      contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file

    # Pull the Docker image (change this to the correct source image)
    - name: Pull Docker Image
      run: |
        docker pull nginx:alpine

    # Tag the image with ACR's tag
    - name: Tag Docker Image
      run: |
        docker tag nginx:alpine myoverlayclusterregistry.azurecr.io/nginx:alpine  # Replace with your image name

    # Push the image to ACR
    - name: Push Docker Image to ACR
      run: |
        docker push myoverlayclusterregistry.azurecr.io/nginx:alpine  # Replace with your image name
